const fs = require('fs');
const content = `export type AppLanguage = "ar" | "fr" | "en";

export const translations = {
  ar: {
    settings: {
      shiftConfig: "إعدادات فترة العمل",
      d1Date: "تاريخ مرجع الدورة (D1)",
      d1Desc: "هذا التاريخ يمثل اليوم الأول (D1) في دورتك",
      shiftSystem: "نظام الدوام",
      sys3x8: "نظام (3×8) الصناعي",
      sys3x8Desc: "دورة من 3 أيام",
      sys5x2: "نظام (5×2) الإداري",
      sys5x2Desc: "أحد - خميس",
      otherSys: "أنظمة أخرى",
      comingSoon: "قريباً...",
      shiftAtRefDate: "فترة العمل في تاريخ المرجع",
      day1Evening: "اليوم الأول: مسائي (13-20)",
      day2MorningNight: "اليوم الثاني: صباحي+ليلي",
      day3Rest: "اليوم الثالث: راحة",
      rotationSystem: "نظام التناوب (Work/Vacation)",
      workDays: "أيام العمل",
      vacationDays: "أيام الإجازة",
      routeDaysTitle: "أيام الطريق (+2)",
      routeDaysDesc: "إضافة يومين للسفر إلى إجازتك",
      annualLeaveTitle: "الإجازة السنوية (30+ يوم)",
      editPool: "تعديل الرصيد",
      remainingPool: "الرصيد المتبقي",
      consumed: "المستهلك",
      addedPeriods: "الفترات المضافة",
      fixedPeriod: "فترة محددة",
      noPeriodsAdded: "لم يتم إضافة أي فترات بعد",
      addAnnualLeave: "إضافة فترة إجازة سنوية",
      welcome: "مرحباً بك!",
      whatsYourName: "أخبرنا ما هو اسمك الكريم؟",
      enterNameHere: "أدخل اسمك هنا...",
      cycleStart: "بداية الدورة",
      whenDidCycleStart: "متى بدأت دورتك الحالية؟",
      shiftType: "نوع فترة العمل",
      whichShiftDidYouHave: "أي فترة عمل كانت لديك في هذا التاريخ؟",
      workSystem: "نظام العمل",
      chooseWorkSystem: "اختر نظام الدوام الخاص بك للاستمرار",
      cycleDuration: "مدة الدورة",
      setWorkVacationDays: "حدد عدد أيام العمل والإجازة",
      stepOutOf: "الخطوة {step} من {total}",
      nextStep: "التالي",
      startUsing: "ابدأ الاستخدام",
      appearanceTitle: "المظهر — لون اللكنة",
      colorBlue: "أزرق",
      colorEmerald: "زمردي",
      colorViolet: "بنفسجي",
      colorAmber: "عنبري",
      colorDesc:
        "يغيّر لون التوهج والحدود النشطة وعناصر التمييز في جميع الشاشات",
      generalPrefs: "التفضيلات العامة",
      notificationsTitle: "الإشعارات",
      notificationsDesc: "تنبيهات فترة العمل والتحولات",
      alertTime: "وقت التنبيه (قبل بـ)",
      hour: "ساعة",
      minute: "د",
      grantPermission: "منح إذن الإشعارات للمتصفح",
      hapticTitle: "الاهتزاز (Haptic)",
      hapticDesc: "ملاحظات لمسية عند التفاعل",
      appLanguage: "لغة التطبيق (Language)",
      dangerZone: "إعادة تعيين كاملة",
      dangerZoneDesc: "مسح كافة الإعدادات والبيانات",
      activate: "تفعيل",
      resetConfirmTitle: "إعادة تعيين البيانات",
      resetConfirmDesc: "هل أنت متأكد من رغبتك في إعادة تعيين كافة البيانات؟",
      cannotUndo: "لا يمكن التراجع عن هذا الإجراء.",
      cancel: "إلغاء",
      deleteAll: "حذف الكل",
      addLeaveTitle: "إضافة فترة إجازة سنوية",
      startDate: "تاريخ البداية",
      usageType: "نوع الاستهلاك",
      all: "الكل",
      half: "النصف",
      custom: "مخصص",
      daysCount: "عدد الأيام",
      example10: "مثلاً: 10",
      add: "إضافة",
      editBalanceTitle: "تعديل رصيد الإجازة السنوية",
      totalDays: "إجمالي الأيام في السنة",
      save: "حفظ",
      by: "بواسطة",
    },
    profile: {
      workHours: "ساعات العمل 🔥",
      goalProgress: "تحقيق الهدف 🚀",
      done: "أنجزت",
      remaining: "تبقي",
      daysPassed: "أيام العمل المنقضية",
      daysRemaining: "أيام العمل المتبقية",
      personalInfo: "المعلومات الشخصية",
      profilePicture: "صورة الملف الشخصي",
      changePicture: "تغيير الصورة",
      deletePicture: "حذف الصورة",
      uploadPicture: "رفع صورة",
      username: "اسم المستخدم",
      enterName: "أدخل اسمك...",
      usernameDesc: "يظهر اسمك في الترحيب وصفحة التقرير الشخصي",
    },
    stats: {
      performanceSummary: "ملخص الأداء الشهري",
      work: "العمل",
      rest: "الراحة",
      vacation: "الإجازة",
      daysDistribution: "توزيع الأيام",
      overviewTab: "نظرة عامة",
      historyTab: "السجل",
      scheduleTab: "القادم",
      todayStatus: "وضعية اليوم",
      enjoyDay: "استمتع بيومك ✨",
      deservedRest: "يوم راحة مستحق 🛡️",
      workHoursText: "{hours} ساعات عمل",
      annualLeaves: "الإجازات السنوية",
      onVacation: "أنت في إجازة 🎉",
      scheduled: "مجدولة",
      remainingTime: "باقي {days} يوم و {hours} س",
      remainingHrs: "باقي {hours} س و {mins} د",
      remainingMins: "متبقي {mins} دقيقة",
      dayInCycle: "اليوم في الدورة",
      dayInVacation: "اليوم في الإجازة",
      current: "الحالية",
      totalYear: "إجمالي السنة",
      remaining: "متبقية",
      untilNextVacation: "⏳ حتى الإجازة القادمة",
      daysText: "يوم",
      workCycleProgress: "تقدم دورة العمل",
      elapsed: "منقضي",
      annualLeaveBalance: "رصيد الإجازة السنوية",
      consumedText: "مستهلك",
      currentMonthDist: "توزيع الشهر الحالي",
      keyMetrics: "ساعات العمل هذا الشهر",
      monthText: "شهر",
      nightShifts: "مناوبات ليلية",
      thisMonthText: "هذا الشهر",
      completedShifts: "مناوبات أُكملت",
      completedText: "تم إكمالها",
      longestStreak: "أطول سلسلة عمل",
      continuousText: "متواصل",
      last14Days: "آخر 14 يوم",
      next14Days: "الجدول القادم (14 يوم)",
      analyticsEngine: "Trois Huit Analytics Engine",
    },
    nav: {
      home: "الرئيسية",
      agenda: "الجدول",
      stats: "الإحصاء",
      health: "الصحة",
      settings: "الإعدادات",
      profile: "الملف",
    },
    shifts: {
      day: "صباحي + ليلي",
      evening: "مسائي",
      night: "ليلي",
      rest: "راحة",
      leave: "إجازة",
      dayShort: "صباحي+ليلي",
    },
    home: {
      untilNextShift: "حتى ورديتك القادمة",
      vacation: "إجازة",
      workCycle: "دورة العمل",
      day: "يوم",
      hoursRemaining: "ساعة متبقية",
      calibrationMenu: "معايرة الجدول (يدوي)",
      startedWorkToday: "بدأت العمل اليوم",
      startedVacationToday: "بدأت الإجازة اليوم",
    },
    agenda: {
      selectedDayDetails: "تفاصيل اليوم المختار",
      exploreSchedule: "استكشف جدولك",
      exploreScheduleDesc: "اختر يوماً من الشريط العلوي أو افتح التقويم الكامل لمشاهدة تفاصيل المناوبات المستقبلية والسابقة.",
      agendaTitle: "تقويم فترة العمل",
      downloadMonthSchedule: "تحميل جدول الشهر",
      download: "تحميل",
      compactView: "عرض مصغر",
      monthView: "عرض الشهر",
      newFeatureTitle: "ميزة جديدة: معايرة الجدول 🧭",
      newFeatureDesc: "يمكنك الآن تصحيح جدولك يدوياً في حال المرض، ضياع الرحلات، أو العمل الإضافي. اضغط على أيقونة البوصلة أعلاه!",
    },
    calibration: {
      manualCalibration: "معايرة الجدول (يدوي)",
      startedWork: "بدأت العمل اليوم",
      startedWorkDesc:
        "ضبط اليوم كبداية دورة العمل بعد العودة من الإجازة أو المرض",
      startedVacation: "بدأت الإجازة اليوم",
      startedVacationDesc:
        "ضبط اليوم كبداية فترة الإجازة (15 يوم) في حال بدأت مبكراً",
      rotationOffset: "إزاحة التناوب (Rotation Offset)",
      delayOneDay: "تأخير يوم واحد",
      advanceOneDay: "تقديم يوم واحد",
      confirmCalibration: "تأكيد معايرة الجدول",
      confirmSyncWork:
        "سيتم ضبط تاريخ بداية دورتك ليكون اليوم. هذا سيعيد ضبط كافة حسابات العمل القادمة والمستقبلية لتبدأ من الآن.",
      confirmSyncVacation:
        "سيتم ضبط جدولك لتبدأ فترة الإجازة من اليوم. سيتم احتساب أيام الإجازة الكاملة بدءاً من هذا التاريخ.",
      confirmShiftPlus:
        "سيتم تقديم الجدول بالكامل بمقدار يوم واحد. سيتحرك كل شيء في التقويم للامام.",
      confirmShiftMinus:
        "سيتم تأخير الجدول بالكامل بمقدار يوم واحد. سيتحرك كل شيء في التقويم للخلف.",
      cancel: "تراجع",
      confirm: "تأكيد",
    },
    extension: {
      title: "تمديد فترة العمل الحالية",
      desc: "إذا كنت ترغب في العمل لأيام إضافية بعد انتهاء الـ {days} يوماً المقررة، يمكنك إضافة تلك الأيام هنا. سيتم دفع موعد إجازتك القادمة وتحديث الإحصائيات تلقائياً.",
      extraDays: "أيام إضافية",
      extendedTo: "تم تمديد العمل إلى",
      daysText: "يوماً.",
      reset: "إعادة الضبط",
      close: "إغلاق",
    },
    announcements: {
      vacationUpdateTitle: "تحديث: تنظيم الإجازة السنوية 🌴",
      vacationUpdateDesc:
        "قمنا بتحسين واجهة إضافة الإجازات السنوية. يمكنك الآن اختيار (الكل، النصف، أو مخصص) مع حساب تلقائي للأيام المتبقية في رصيدك.",
    },
    card: {
      currentStatus: "الحالة الحالية",
      todayDetails: "تفاصيل اليوم",
      onVacationNow: "أنت الآن في فترة إجازة 🌴",
      vacationDay: "يوم إجازة 🌴",
      onRestNow: "أنت في يوم راحة 🛡️",
      restDay: "يوم راحة 🛡️",
      period: "فترة",
      resumeAt: "الاستئناف:",
      next: "التالي:",
      inDays: "بعد {days} يوم",
    },
    header: {
      goodMorning: "صباح الخير",
      goodDay: "طاب يومك",
      goodEvening: "مساء الخير",
      goodNight: "ليلة سعيدة",
      coworker: "زميل العمل",
      personalInfo: "المعلومات الشخصية",
      viewProfile: "عرض الملف الشخصي",
      settings: "الإعدادات",
      appSettings: "إعدادات التطبيق",
      notifications: "الإشعارات",
      noNotifications: "لا توجد إشعارات حالياً",
      hide: "إخفاء",
      shareTitle: "Trois Huit - جدول المناوبات",
      shareText:
        "ودّع فوضى جداول العمل، واستقبل تنظيماً أكثر كفاءة واحترافية مع تطبيق Trois Huit — المساعد الذكي لإدارة نظام المناوبات.\\n\\nماذا يقدّم لك التطبيق؟\\n\\n✅ حساب دقيق وفوري لجداول المناوبات وفق نظام عملك.\\n🌴 إدارة تلقائية لرصيد الإجازات الشهرية والسنوية بكل شفافية.\\n📅 أجندة متكاملة تتضمن العطل الوطنية والمناسبات الإسلامية لتخطيط أفضل.\\n🔔 تنبيهات وإشعارات فورية لضمان عدم تفويت أي موعد أو مناوبة.\\n\\nتطبيق خفيف وسهل الاستخدام، لا يتطلب إنشاء حساب، ومتاح مجاناً بالكامل.\\n\\nابدأ الآن بتنظيم وقتك بكفاءة أعلى، وشاركه مع زملائك ليستفيد الجميع.",
      shareUrlText: "الرابط: ",
    },
    health: {
      title: "الصحة والنوم",
      subtitle: "نصائح وإرشادات للتعامل مع نظام 3x8",
      recommendations: "توصيات مخصصة",
      currentPeriod: "الفترة الحالية",
      currentShift: "المناوبة الحالية",
      morningTitle: "صحة الوردية الصباحية",
      morningTip1: "نم مبكراً الليلة السابقة. اهدف إلى 7-8 ساعات من النوم.",
      morningTip2: "تناول القهوة قبل 10 صباحاً لتجنب اضطراب النوم.",
      morningTip3: "خذ قيلولة قصيرة (20-30 دقيقة) بعد العمل إذا كنت متعباً.",
      eveningTitle: "صحة الوردية المسائية",
      eveningTip1: "نم في وقت متأخر صباحاً. حافظ على جدول منتظم.",
      eveningTip2: "مارس الرياضة قبل الذهاب للعمل، وليس بعده.",
      eveningTip3: "تجنب الوجبات الثقيلة قبل النوم ليلاً.",
      nightTitle: "صحة الوردية الليلية",
      nightTip1: "تجنب الكافيين بعد 4 فجراً.",
      nightTip2: "تناول وجبات خفيفة ليلاً لتسهيل الهضم.",
      nightTip3: "ارتدِ نظارات شمسية عند العودة للمنزل صباحاً.",
      restTitle: "صحة يوم الراحة",
      restTip1: "تعافَ! خذ قيلولة استشفاء (8-13) في يوم الراحة الأول.",
      restTip2: "عُد تدريجياً لجدول النهار الطبيعي.",
      restTip3: "تعرض للشمس لضبط ساعتك البيولوجية.",
      generalTitle: "نصائح صحية عامة",
      generalTip1: "حافظ على ترطيب جسمك.",
      generalTip2: "تناول وجبات متوازنة.",
      generalTip3: "اهدف إلى 7-9 ساعات من النوم كل 24 ساعة.",
    },
  },
  fr: {
    settings: {
      shiftConfig: "Configuration des Postes",
      d1Date: "Date de référence (D1)",
      d1Desc: "Cette date représente le premier jour (D1) de votre cycle",
      shiftSystem: "Système de travail",
      sys3x8: "Système (3x8) Industriel",
      sys3x8Desc: "Cycle de 3 jours",
      sys5x2: "Système (5x2) Administratif",
      sys5x2Desc: "Dimanche - Jeudi",
      otherSys: "Autres systèmes",
      comingSoon: "Bientôt...",
      shiftAtRefDate: "Poste à la date de référence",
      day1Evening: "Jour 1: Soir (13h-20h)",
      day2MorningNight: "Jour 2: Matin+Nuit",
      day3Rest: "Jour 3: Repos",
      rotationSystem: "Système de Rotation (Travail/Congé)",
      workDays: "Jours de travail",
      vacationDays: "Jours de congé",
      routeDaysTitle: "Jours de route (+2)",
      routeDaysDesc: "Ajouter vos deux jours de voyage au congé",
      annualLeaveTitle: "Congé Annuel (30+ jours)",
      editPool: "Modifier Solde",
      remainingPool: "Solde",
      consumed: "Consommé",
      addedPeriods: "Périodes ajoutées",
      fixedPeriod: "Période fixée",
      noPeriodsAdded: "Aucune période ajoutée",
      addAnnualLeave: "Ajouter un congé annuel",
      welcome: "Bienvenue !",
      whatsYourName: "Quel est votre nom ?",
      enterNameHere: "Entrez votre nom...",
      cycleStart: "Début du cycle",
      whenDidCycleStart: "Quand a commencé votre cycle actuel ?",
      shiftType: "Type de poste",
      whichShiftDidYouHave: "Quel poste aviez-vous à cette date ?",
      workSystem: "Système de travail",
      chooseWorkSystem: "Choisissez votre système de travail",
      cycleDuration: "Durée du cycle",
      setWorkVacationDays: "Définissez les jours de travail et de congé",
      stepOutOf: "Étape {step} sur {total}",
      nextStep: "Suivant",
      startUsing: "Commencer",
      appearanceTitle: "Apparence - Couleur d'accentuation",
      colorBlue: "Bleu",
      colorEmerald: "Émeraude",
      colorViolet: "Violet",
      colorAmber: "Ambre",
      colorDesc: "Change la couleur des accents sur tous les écrans",
      generalPrefs: "Préférences générales",
      notificationsTitle: "Notifications",
      notificationsDesc: "Alertes pour les postes et transitions",
      alertTime: "Heure d'alerte (avant)",
      hour: "heure",
      minute: "min",
      grantPermission: "Accorder la permission",
      hapticTitle: "Retour Haptique",
      hapticDesc: "Retours tactiles lors de l'interaction",
      appLanguage: "Langue (Language)",
      dangerZone: "Réinitialisation complète",
      dangerZoneDesc: "Effacer tous les paramètres et données",
      activate: "Activer",
      resetConfirmTitle: "Réinitialiser les données",
      resetConfirmDesc:
        "Êtes-vous sûr de vouloir réinitialiser toutes les données?",
      cannotUndo: "Cette action est irréversible.",
      cancel: "Annuler",
      deleteAll: "Tout supprimer",
      addLeaveTitle: "Ajouter un congé",
      startDate: "Date de début",
      usageType: "Type de consommation",
      all: "Tout",
      half: "Moitié",
      custom: "Personnalisé",
      daysCount: "Nombre de jours",
      example10: "Ex: 10",
      add: "Ajouter",
      editBalanceTitle: "Modifier le solde",
      totalDays: "Total des jours par an",
      save: "Enregistrer",
      by: "Par",
    },
    profile: {
      workHours: "Heures Travaillées 🔥",
      goalProgress: "Objectif Atteint 🚀",
      done: "Accompli",
      remaining: "Restant",
      daysPassed: "Jours passés",
      daysRemaining: "Jours restants",
      personalInfo: "Informations personnelles",
      profilePicture: "Photo de profil",
      changePicture: "Changer l'image",
      deletePicture: "Supprimer",
      uploadPicture: "Télécharger",
      username: "Nom d'utilisateur",
      enterName: "Entrez votre nom...",
      usernameDesc: "Votre nom apparaît sur l'écran d'accueil",
    },
    stats: {
      performanceSummary: "Résumé Mensuel",
      work: "Travail",
      rest: "Repos",
      vacation: "Congé",
      daysDistribution: "Distribution des Jours",
      overviewTab: "Aperçu",
      historyTab: "Historique",
      scheduleTab: "À venir",
      todayStatus: "Statut du Jour",
      enjoyDay: "Profitez de votre jour ✨",
      deservedRest: "Repos bien mérité 🛡️",
      workHoursText: "{hours} Heures de travail",
      annualLeaves: "Congés Annuels",
      onVacation: "Vous êtes en congé 🎉",
      scheduled: "Planifié",
      remainingTime: "Reste {days}j et {hours}h",
      remainingHrs: "Reste {hours}h et {mins}m",
      remainingMins: "Reste {mins} min",
      dayInCycle: "Jour de Cycle",
      dayInVacation: "Jour de Congé",
      current: "Actuel",
      totalYear: "Total Annuel",
      remaining: "Restant",
      untilNextVacation: "⏳ Jusqu'au prochain congé",
      daysText: "Jour(s)",
      workCycleProgress: "Progression du Cycle",
      elapsed: "Écoulé",
      annualLeaveBalance: "Solde Congé Annuel",
      consumedText: "Consommé",
      currentMonthDist: "Distribution du Mois",
      keyMetrics: "Heures ce mois",
      monthText: "Mois",
      nightShifts: "Postes de nuit",
      thisMonthText: "Ce mois",
      completedShifts: "Postes complétés",
      completedText: "Terminé",
      longestStreak: "Série la plus longue",
      continuousText: "Continu",
      last14Days: "14 Derniers Jours",
      next14Days: "Prochains 14 Jours",
      analyticsEngine: "Trois Huit Analytics Engine",
    },
    nav: {
      home: "Accueil",
      agenda: "Agenda",
      stats: "Stats",
      health: "Santé",
      settings: "Paramètres",
      profile: "Profil",
    },
    shifts: {
      day: "Matin + Nuit",
      evening: "Soir",
      night: "Nuit",
      rest: "Repos",
      leave: "Congé",
      dayShort: "Matin+Nuit",
    },
    home: {
      untilNextShift: "Avant la prochaine rotation",
      vacation: "Congé",
      workCycle: "Cycle de travail",
      day: "Jour",
      hoursRemaining: "h restantes",
      calibrationMenu: "Calibration (Manuelle)",
      startedWorkToday: "J'ai commencé le travail aujourd'hui",
      startedVacationToday: "J'ai commencé le congé aujourd'hui",
    },
    agenda: {
      selectedDayDetails: "Détails du jour sélectionné",
      exploreSchedule: "Découvrez votre planning",
      exploreScheduleDesc: "Sélectionnez un jour dans la barre ou ouvrez l'agenda.",
      agendaTitle: "Calendrier de Travail",
      downloadMonthSchedule: "Télécharger le mois",
      download: "Télécharger",
      compactView: "Vue compacte",
      monthView: "Vue du mois",
      newFeatureTitle: "Nouveau : Calibration 🧭",
      newFeatureDesc: "Vous pouvez désormais corriger manuellement votre horaire. Appuyez sur la boussole !",
    },
    calibration: {
      manualCalibration: "Calibration Manuelle",
      startedWork: "Travail commencé aujourd'hui",
      startedWorkDesc: "Définir aujourd'hui comme début du cycle",
      startedVacation: "Congé commencé aujourd'hui",
      startedVacationDesc: "Définir aujourd'hui comme début de vos congés",
      rotationOffset: "Décalage de Rotation",
      delayOneDay: "Retarder d'un jour",
      advanceOneDay: "Avancer d'un jour",
      confirmCalibration: "Confirmer la Calibration",
      confirmSyncWork: "Ceci redéfinira votre début de cycle à aujourd'hui.",
      confirmSyncVacation: "Ceci débutera votre congé à partir d'aujourd'hui.",
      confirmShiftPlus: "Ceci avancera tout le calendrier d'un jour.",
      confirmShiftMinus: "Ceci retardera tout le calendrier d'un jour.",
      cancel: "Annuler",
      confirm: "Confirmer",
    },
    extension: {
      title: "Extension du Travail",
      desc: "Si vous travaillez plus que les {days} jours, ajoutez les jours ici pour retarder vos futurs congés.",
      extraDays: "Jours Supplémentaires",
      extendedTo: "Travail étendu à",
      daysText: "Jours.",
      reset: "Réinitialiser",
      close: "Fermer",
    },
    announcements: {
      vacationUpdateTitle: "Mise à jour: Congés Annuels 🌴",
      vacationUpdateDesc:
        "Vous pouvez désormais sélectionner le nombre de jours à soustraire (Tout, Moitié, ou Personnalisé).",
    },
    card: {
      currentStatus: "Statut actuel",
      todayDetails: "Détails du jour",
      onVacationNow: "Vous êtes en congé 🌴",
      vacationDay: "Jour de congé 🌴",
      onRestNow: "Vous êtes en repos 🛡️",
      restDay: "Jour de repos 🛡️",
      period: "Poste",
      resumeAt: "Reprise:",
      next: "Suivant:",
      inDays: "Dans {days} jours",
    },
    header: {
      goodMorning: "Bonjour",
      goodDay: "Bonne journée",
      goodEvening: "Bonsoir",
      goodNight: "Bonne nuit",
      coworker: "Collègue",
      personalInfo: "Informations personnelles",
      viewProfile: "Voir le profil",
      settings: "Paramètres",
      appSettings: "Paramètres de l'application",
      notifications: "Notifications",
      noNotifications: "Aucune notification",
      hide: "Cacher",
      shareTitle: "Trois Huit - Agenda",
      shareText: "L'application ultime pour la gestion des postes de 3x8.",
      shareUrlText: "Lien: ",
    },
    health: {
      title: "Santé & Sommeil",
      subtitle: "Conseils pour le rythme 3x8",
      recommendations: "Recommandations personnalisées",
      currentPeriod: "Période actuelle",
      currentShift: "Poste actuel",
      morningTitle: "Santé - Poste du Matin",
      morningTip1: "Dormez tôt la veille. Visez 7-8h de sommeil.",
      morningTip2:
        "Buvez du café avant 10h pour éviter de perturber votre sommeil.",
      morningTip3:
        "Faites une courte sieste (20-30 min) après le travail si vous êtes fatigué.",
      eveningTitle: "Santé - Poste du Soir",
      eveningTip1: "Dormez tard le matin. Gardez un horaire régulier.",
      eveningTip2: "Faites de l'exercice avant d'aller au travail, pas après.",
      eveningTip3: "Évitez les repas lourds juste avant de dormir la nuit.",
      nightTitle: "Santé - Poste de Nuit",
      nightTip1: "Évitez la caféine après 4h du matin.",
      nightTip2: "Mangez léger pendant la nuit pour faciliter la digestion.",
      nightTip3:
        "Portez des lunettes de soleil en rentrant chez vous le matin.",
      restTitle: "Santé - Jour de Repos",
      restTip1:
        "Récupérez ! Faites une sieste de guérison (8h-13h) le premier jour de repos.",
      restTip2: "Revenez progressivement à un horaire de jour normal.",
      restTip3: "Profitez du soleil pour réinitialiser votre rythme circadien.",
      generalTitle: "Conseils Généraux",
      generalTip1: "Maintenez une hydratation adéquate.",
      generalTip2: "Ayez une alimentation équilibrée.",
      generalTip3: "Visez 7 à 9 heures de sommeil par 24 heures.",
    },
  },
  en: {
    settings: {
      shiftConfig: "Shift Configuration",
      d1Date: "Reference Date (D1)",
      d1Desc: "This date represents the first day (D1) in your cycle",
      shiftSystem: "Shift System",
      sys3x8: "Industrial (3x8) System",
      sys3x8Desc: "3-day cycle",
      sys5x2: "Administrative (5x2) System",
      sys5x2Desc: "Sun - Thu",
      otherSys: "Other systems",
      comingSoon: "Coming soon...",
      shiftAtRefDate: "Shift at Reference Date",
      day1Evening: "Day 1: Evening (13h-20h)",
      day2MorningNight: "Day 2: Morn+Night",
      day3Rest: "Day 3: Rest",
      rotationSystem: "Rotation System (Work/Vacation)",
      workDays: "Work Days",
      vacationDays: "Vacation Days",
      routeDaysTitle: "Route Days (+2)",
      routeDaysDesc: "Add two travel days to your vacation",
      annualLeaveTitle: "Annual Leave (30+ days)",
      editPool: "Edit Balance",
      remainingPool: "Remaining",
      consumed: "Consumed",
      addedPeriods: "Added Periods",
      fixedPeriod: "Fixed Period",
      noPeriodsAdded: "No periods added yet",
      addAnnualLeave: "Add annual leave",
      welcome: "Welcome!",
      whatsYourName: "What is your name?",
      enterNameHere: "Enter your name...",
      cycleStart: "Cycle Start",
      whenDidCycleStart: "When did your current cycle start?",
      shiftType: "Shift Type",
      whichShiftDidYouHave: "Which shift did you have on this date?",
      workSystem: "Work System",
      chooseWorkSystem: "Choose your work system to continue",
      cycleDuration: "Cycle Duration",
      setWorkVacationDays: "Set work and vacation days",
      stepOutOf: "Step {step} of {total}",
      nextStep: "Next",
      startUsing: "Start Using",
      appearanceTitle: "Appearance - Accent Color",
      colorBlue: "Blue",
      colorEmerald: "Emerald",
      colorViolet: "Violet",
      colorAmber: "Amber",
      colorDesc: "Changes the accent color across all screens",
      generalPrefs: "General Preferences",
      notificationsTitle: "Notifications",
      notificationsDesc: "Alerts for shifts and transitions",
      alertTime: "Alert Time (Before)",
      hour: "hour",
      minute: "min",
      grantPermission: "Grant Permission",
      hapticTitle: "Haptic Feedback",
      hapticDesc: "Tactile feedback on interaction",
      appLanguage: "App Language",
      dangerZone: "Full Reset",
      dangerZoneDesc: "Clear all settings and data",
      activate: "Activate",
      resetConfirmTitle: "Reset Data",
      resetConfirmDesc: "Are you sure you want to reset all data?",
      cannotUndo: "This action cannot be undone.",
      cancel: "Cancel",
      deleteAll: "Delete All",
      addLeaveTitle: "Add Annual Leave",
      startDate: "Start Date",
      usageType: "Usage Type",
      all: "All",
      half: "Half",
      custom: "Custom",
      daysCount: "Days Count",
      example10: "E.g. 10",
      add: "Add",
      editBalanceTitle: "Edit Leave Balance",
      totalDays: "Total Days per Year",
      save: "Save",
      by: "By",
    },
    profile: {
      workHours: "Hours Worked 🔥",
      goalProgress: "Goal Progress 🚀",
      done: "Done",
      remaining: "Remaining",
      daysPassed: "Days Passed",
      daysRemaining: "Days Remaining",
      personalInfo: "Personal Information",
      profilePicture: "Profile Picture",
      changePicture: "Change Picture",
      deletePicture: "Delete",
      uploadPicture: "Upload",
      username: "Username",
      enterName: "Enter your name...",
      usernameDesc: "Appears on the welcome screen",
    },
    stats: {
      performanceSummary: "Monthly Summary",
      work: "Work",
      rest: "Rest",
      vacation: "Vacation",
      daysDistribution: "Days Distribution",
      overviewTab: "Overview",
      historyTab: "History",
      scheduleTab: "Schedule",
      todayStatus: "Today's Status",
      enjoyDay: "Enjoy your day ✨",
      deservedRest: "Deserved rest 🛡️",
      workHoursText: "{hours} Work hours",
      annualLeaves: "Annual Leaves",
      onVacation: "You're on vacation 🎉",
      scheduled: "Scheduled",
      remainingTime: "{days}d {hours}h remaining",
      remainingHrs: "{hours}h {mins}m remaining",
      remainingMins: "{mins} mins remaining",
      dayInCycle: "Day in Cycle",
      dayInVacation: "Day in Vacation",
      current: "Current",
      totalYear: "Total Year",
      remaining: "Remaining",
      untilNextVacation: "⏳ Until Next Vacation",
      daysText: "Day(s)",
      workCycleProgress: "Cycle Progress",
      elapsed: "Elapsed",
      annualLeaveBalance: "Annual Leave Balance",
      consumedText: "Consumed",
      currentMonthDist: "Monthly Distribution",
      keyMetrics: "Hours This Month",
      monthText: "Month",
      nightShifts: "Night Shifts",
      thisMonthText: "This Month",
      completedShifts: "Completed Shifts",
      completedText: "Completed",
      longestStreak: "Longest Streak",
      continuousText: "Continuous",
      last14Days: "Last 14 Days",
      next14Days: "Next 14 Days",
      analyticsEngine: "Trois Huit Analytics Engine",
    },
    nav: {
      home: "Home",
      agenda: "Agenda",
      stats: "Stats",
      health: "Health",
      settings: "Settings",
      profile: "Profile",
    },
    shifts: {
      day: "Morning + Night",
      evening: "Evening",
      night: "Night",
      rest: "Rest",
      leave: "Leave",
      dayShort: "Morn+Night",
    },
    home: {
      untilNextShift: "Until next shift",
      vacation: "Vacation",
      workCycle: "Work Cycle",
      day: "Day",
      hoursRemaining: "h remaining",
      calibrationMenu: "Manual Calibration",
      startedWorkToday: "Started work today",
      startedVacationToday: "Started vacation today",
    },
    agenda: {
      selectedDayDetails: "Selected Day Details",
      exploreSchedule: "Explore Your Schedule",
      exploreScheduleDesc: "Select a day from the top bar or open calendar.",
      agendaTitle: "Work Schedule",
      downloadMonthSchedule: "Download Month",
      download: "Download",
      compactView: "Compact View",
      monthView: "Month View",
      newFeatureTitle: "New: Schedule Calibration 🧭",
      newFeatureDesc: "You can now manually adjust your schedule. Tap the compass icon above!",
    },
    calibration: {
      manualCalibration: "Manual Calibration",
      startedWork: "Started Work Today",
      startedWorkDesc: "Set today as cycle start",
      startedVacation: "Started Vacation Today",
      startedVacationDesc: "Set today as vacation start",
      rotationOffset: "Rotation Offset",
      delayOneDay: "Delay by 1 Day",
      advanceOneDay: "Advance by 1 Day",
      confirmCalibration: "Confirm Calibration",
      confirmSyncWork: "This will set your cycle start date to today.",
      confirmSyncVacation: "This will start your vacation period from today.",
      confirmShiftPlus: "This will advance the calendar by one day.",
      confirmShiftMinus: "This will delay the calendar by one day.",
      cancel: "Cancel",
      confirm: "Confirm",
    },
    extension: {
      title: "Active Work Extension",
      desc: "If you work beyond the scheduled {days} days, add the days here to delay your next vacation.",
      extraDays: "Extra Days",
      extendedTo: "Extended to",
      daysText: "Days.",
      reset: "Reset",
      close: "Close",
    },
    announcements: {
      vacationUpdateTitle: "Update: Annual Leaves 🌴",
      vacationUpdateDesc:
        "You can now properly deduct custom quantities of your total leave balance.",
    },
    card: {
      currentStatus: "Current Status",
      todayDetails: "Today's Details",
      onVacationNow: "You are on vacation 🌴",
      vacationDay: "Vacation Day 🌴",
      onRestNow: "You are on a rest day 🛡️",
      restDay: "Rest Day 🛡️",
      period: "Shift:",
      resumeAt: "Resume:",
      next: "Next:",
      inDays: "In {days} days",
    },
    header: {
      goodMorning: "Good Morning",
      goodDay: "Good Day",
      goodEvening: "Good Evening",
      goodNight: "Good Night",
      coworker: "Coworker",
      personalInfo: "Personal Information",
      viewProfile: "View Profile",
      settings: "Settings",
      appSettings: "App Settings",
      notifications: "Notifications",
      noNotifications: "No notifications currently",
      hide: "Hide",
      shareTitle: "Trois Huit - Schedule",
      shareText: "The ultimate 3x8 shift schedule manager.",
      shareUrlText: "Link: ",
    },
    health: {
      title: "Health & Sleep",
      subtitle: "Tips for the 3x8 shift pattern",
      recommendations: "Personalized Recommendations",
      currentPeriod: "Current Period",
      currentShift: "Current Shift",
      morningTitle: "Morning Shift Health",
      morningTip1: "Sleep early the night before. Aim for 7-8h of sleep.",
      morningTip2: "Drink coffee before 10 AM to avoid disrupting sleep.",
      morningTip3: "Take a short nap (20-30 min) after work if tired.",
      eveningTitle: "Evening Shift Health",
      eveningTip1: "Sleep late in the morning. Keep a regular schedule.",
      eveningTip2: "Exercise before going to work, not after.",
      eveningTip3: "Avoid heavy meals just before sleeping at night.",
      nightTitle: "Night Shift Health",
      nightTip1: "Avoid caffeine after 4 AM.",
      nightTip2: "Eat light snacks at night to aid digestion.",
      nightTip3: "Wear sunglasses when returning home in the morning.",
      restTitle: "Rest Day Health",
      restTip1: "Recover! Take a healing nap (8-13h) on your first rest day.",
      restTip2: "Gradually return to a normal daytime schedule.",
      restTip3: "Get sun exposure to reset your biological clock.",
      generalTitle: "General Health Tips",
      generalTip1: "Stay hydrated.",
      generalTip2: "Eat balanced meals.",
      generalTip3: "Aim for 7-9 hours of sleep per 24 hours.",
    },
  },
};

export function getTranslation(lang: AppLanguage) {
  return translations[lang] || translations.en;
}
`;

fs.writeFileSync(path.join(__dirname, 'rebuild_i18n.js'), `
const fs = require('fs');
fs.writeFileSync(${'`' + p('lib/i18n.ts') + '`'}, ${'`${content}`'}, 'utf8');
`, 'utf8');
